services:
  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    stdin_open: true
    depends_on:
      - backend
    networks:
      - react-express

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "3001:3000"  # expõe porta 3000 do container na 3001 local
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/db
    networks:
      - express-mongo
      - react-express

  mongo:
    image: mongo:4.2.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - express-mongo

volumes:
  mongo_data:

networks:
  react-express:
  express-mongo:
